services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
  frontend:
    build:
      dockerfile: web.prod.Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
  redis:
    image: redis
